### ISSUE TITLE
Protótipo do tabuleiro

### ISSUE THREAD

**Issue by aurora-carvalho** [unimonte-games/festa-dos-duendes#5]
Protótipo físico do tabuleiro.
- Quadro/reto (sem curvas);
- Com possibilidades de diversos caminhos;

**Comment by Andre-LA** [comment]
Início do gerador de tabuleiro criado pelo Nicolas no commit d7a57024d13a3712ba0580dec2eb8d351d5e046b

**Comment by Andre-LA** [comment]
_Andamento: Um protótipo físico foi criado no dia 29 de agosto pelo Nicolas e testado no dia 30._
